version: "3.8"

services:
  app:
    build: .
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@db:5432/image_processing_system_db
      REDIS_URL: redis://redis:6379
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: image_processing_system_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  worker:
    build: .
    command: ["celery", "-A", "app.workers.celery.celery", "worker", "--loglevel=info"]
    depends_on:
      - redis
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@db:5432/image_processing_system_db
      REDIS_URL: redis://redis:6379
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    volumes:
      - ./uploads:/app/uploads

volumes:
  pg_data: