"""Initial migration

Revision ID: c7ea090f3e84
Revises: 
Create Date: 2025-02-24 08:44:47.753206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7ea090f3e84'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_requests',
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_processing_requests_request_id'), 'processing_requests', ['request_id'], unique=False)
    op.create_table('processed_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('serial_number', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('input_images', sa.Text(), nullable=False),
    sa.Column('output_images', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['processing_requests.request_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_images')
    op.drop_index(op.f('ix_processing_requests_request_id'), table_name='processing_requests')
    op.drop_table('processing_requests')
    # ### end Alembic commands ###
